import dayjs from 'dayjs/esm';

import { IOrders, NewOrders } from './orders.model';

export const sampleWithRequiredData: IOrders = {
  id: 13099,
  cart: 'mellow weaken thankfully',
  totalQty: 'tightly about playful',
  payAmount: 24162.29,
  orderNumber: 'oxidise zowie derby',
  paymentStatus: 'thrifty or rainy',
  customerEmail: 'uh-huh',
  customerName: 'flip-flops',
  customerCountry: 'writhe trap',
  customerPhone: 'meld till',
  status: 'cornerstone birth ouch',
  currencySign: 'constrict consequently',
  currencyValue: 28806.39,
  shippingCost: 5119.52,
  packingCost: 7330.38,
  tax: 32667.56,
  dp: true,
  vendorShippingId: 27927,
  vendorPackingId: 28147,
  wholeDiscount: 4085.84,
};

export const sampleWithPartialData: IOrders = {
  id: 16593,
  userId: 20771,
  cart: 'anenst out',
  shipping: 'willfully mediocre',
  totalQty: 'but strap turban',
  payAmount: 11741.38,
  orderNumber: 'footrest dude explicate',
  paymentStatus: 'flimsy',
  customerEmail: 'till ugh',
  customerName: 'until fold meh',
  customerCountry: 'bore glucose times',
  customerPhone: 'jubilantly',
  shippingName: 'broker',
  shippingCountry: 'centralise',
  shippingEmail: 'defender',
  shippingCity: 'officially geez',
  shippingZip: 'birth righteously eek',
  orderNote: 'who fancy duh',
  couponCode: 'utterly',
  couponDiscount: 'pumpernickel',
  status: 'amass',
  updatedAt: dayjs('2023-12-02T04:25'),
  affilateUser: 'reborn',
  affilateCharge: 'distill',
  currencySign: 'hideous',
  currencyValue: 27953.66,
  shippingCost: 23762.29,
  packingCost: 26731.16,
  tax: 333.37,
  dp: false,
  vendorShippingId: 18725,
  vendorPackingId: 1101,
  wholeDiscount: 29519.16,
};

export const sampleWithFullData: IOrders = {
  id: 4720,
  userId: 7515,
  cart: 'previous for',
  method: 'huzzah black',
  shipping: 'moai',
  pickupLocation: 'yowza failing',
  totalQty: 'tightly',
  payAmount: 31542.63,
  txnid: 'relieved indeed',
  chargeId: 'tender hm circa',
  orderNumber: 'oh ascribe squish',
  paymentStatus: 'phooey',
  customerEmail: 'duh fortunately',
  customerName: 'ack ew',
  customerCountry: 'wonderfully',
  customerPhone: 'and considering approval',
  customerAddress: 'invoke generously',
  customerCity: 'untimely platinum fully',
  customerZip: 'whoa qua an',
  shippingName: 'aw comeback',
  shippingCountry: 'truthfully if',
  shippingEmail: 'vice',
  shippingPhone: 'reasonable',
  shippingAddress: 'limping hippodrome although',
  shippingCity: 'proud rust quizzically',
  shippingZip: 'monstrous officially weakly',
  orderNote: 'relief over without',
  couponCode: 'downgrade lest meanwhile',
  couponDiscount: 'including enumerate',
  status: 'scarcely kindness bone',
  createdAt: dayjs('2023-12-02T08:17'),
  updatedAt: dayjs('2023-12-02T15:01'),
  affilateUser: 'defame',
  affilateCharge: 'until',
  currencySign: 'pro',
  currencyValue: 23263.95,
  shippingCost: 31864.26,
  packingCost: 14836.47,
  tax: 28529.3,
  dp: false,
  payId: 'brr before',
  vendorShippingId: 16099,
  vendorPackingId: 30706,
  wholeDiscount: 13254.59,
};

export const sampleWithNewData: NewOrders = {
  cart: 'where hoard acclaimed',
  totalQty: 'round kiddingly',
  payAmount: 27625.24,
  orderNumber: 'on behind rightfully',
  paymentStatus: 'than boo alarmed',
  customerEmail: 'heavily',
  customerName: 'fleck since',
  customerCountry: 'but faff paralyze',
  customerPhone: 'wherever',
  status: 'posture while prevent',
  currencySign: 'polite drat',
  currencyValue: 17773.82,
  shippingCost: 28170.08,
  packingCost: 32461.44,
  tax: 16889.79,
  dp: true,
  vendorShippingId: 10167,
  vendorPackingId: 22399,
  wholeDiscount: 1592.56,
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
