import dayjs from 'dayjs/esm';

import { IUsers, NewUsers } from './users.model';

export const sampleWithRequiredData: IUsers = {
  id: 12244,
  name: 'installation arthur',
  email: 'Rosie.Franey@gmail.com',
  status: true,
  affilateIncome: 4426.46,
  isVendor: false,
  fCheck: false,
  gCheck: true,
  tCheck: false,
  lCheck: true,
  mailSent: false,
  shippingCost: 13800.56,
  currentBalance: 19182.52,
  ban: false,
};

export const sampleWithPartialData: IUsers = {
  id: 7947,
  name: 'and',
  photo: 'abaft',
  zip: 'vitality although',
  country: 'Colombia',
  fax: 'oof',
  email: 'Myrna_Franey@yahoo.com',
  password: 'french kookily afore',
  updatedAt: dayjs('2023-12-01'),
  isProvider: true,
  status: true,
  affilateCode: 'procrastinate onto geez',
  affilateIncome: 27280.47,
  shopAddress: 'phooey dolman',
  regNumber: 'provided fooey impractical',
  shopMessage: 'jogging lady',
  shopDetails: 'once nippy',
  shopImage: 'coverall at retch',
  isVendor: true,
  fCheck: true,
  gCheck: true,
  tCheck: false,
  lCheck: false,
  mailSent: false,
  shippingCost: 24327.85,
  currentBalance: 17581.87,
  ban: true,
  isPrinter: true,
};

export const sampleWithFullData: IUsers = {
  id: 19875,
  name: 'since through until',
  photo: 'book against faithfully',
  zip: 'yuck',
  city: 'Quigleyfurt',
  country: 'Monaco',
  address: 'among',
  phone: '1-690-223-8602 x5560',
  fax: 'denote',
  email: 'Joy21@yahoo.com',
  password: 'fishnet',
  rememberToken: 'flat excluding',
  createdAt: dayjs('2023-12-02'),
  updatedAt: dayjs('2023-12-01'),
  isProvider: false,
  status: true,
  verificationLink: 'generally',
  emailVerified: 'starchy pish',
  affilateCode: 'leash',
  affilateIncome: 8979.84,
  shopName: 'douse impolite eek',
  ownerName: 'guilt',
  shopNumber: 'gee hence a',
  shopAddress: 'frankly towards',
  regNumber: 'health',
  shopMessage: 'revolving sturdy',
  shopDetails: 'instead ouch wreck',
  shopImage: 'blabber smoothly barring',
  fUrl: 'concerning fooey',
  gUrl: 'unto beneath',
  tUrl: 'vice fortunately intelligent',
  lUrl: 'once',
  isVendor: false,
  fCheck: true,
  gCheck: true,
  tCheck: false,
  lCheck: true,
  mailSent: true,
  shippingCost: 31169.37,
  currentBalance: 11609.97,
  date: dayjs('2023-12-01'),
  ban: true,
  isPrinter: false,
};

export const sampleWithNewData: NewUsers = {
  name: 'unripe',
  email: 'Stephan.Howe@yahoo.com',
  status: false,
  affilateIncome: 13546.22,
  isVendor: true,
  fCheck: false,
  gCheck: false,
  tCheck: true,
  lCheck: true,
  mailSent: true,
  shippingCost: 20880.57,
  currentBalance: 2995.84,
  ban: true,
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
