import dayjs from 'dayjs/esm';

import { IProducts, NewProducts } from './products.model';

export const sampleWithRequiredData: IProducts = {
  id: 2076,
  name: 'um despite',
  photo: 'solemnly the',
  price: 1404.49,
  status: 21067,
  views: 2042,
  productCondition: 8825,
  isMeta: true,
  type: 'gracious impolite accurate',
  featured: false,
  best: true,
  top: true,
  hot: false,
  latest: false,
  big: true,
  trending: false,
  sale: true,
  isDiscount: false,
  isCatalog: false,
};

export const sampleWithPartialData: IProducts = {
  id: 74,
  sku: 'ha aw unlike',
  productType: 'plug lurch',
  categoryId: 23013,
  subcategoryId: 23475,
  childcategoryId: 7372,
  attributes: 'incidentally language blah',
  name: 'vainly',
  photo: 'accurate',
  size: 'blend secede',
  sizeQty: 'nervously uh-huh which',
  color: 'turquoise',
  price: 22809.37,
  previousPrice: 16440.82,
  details: 'outweigh tenderly phooey',
  stock: 23296,
  policy: 'like since nicely',
  status: 22405,
  views: 8054,
  features: 'so',
  productCondition: 5017,
  ship: 'commission event flip-flops',
  isMeta: false,
  youtube: 'massage provided',
  type: 'naturally loosely',
  license: 'whether before unsightly',
  licenseQty: 'officially',
  region: 'tamp uh-huh',
  featured: true,
  best: true,
  top: false,
  hot: true,
  latest: true,
  big: true,
  trending: true,
  sale: false,
  createdAt: dayjs('2023-12-02T16:29'),
  updatedAt: dayjs('2023-12-01T18:23'),
  isDiscount: true,
  wholeSellDiscount: 'required circa whether',
  isCatalog: true,
};

export const sampleWithFullData: IProducts = {
  id: 28534,
  sku: 'pita sternly',
  productType: 'meek',
  affiliateLink: 'silently',
  userId: 7606,
  categoryId: 28411,
  subcategoryId: 27574,
  childcategoryId: 29126,
  attributes: 'planter shadowy',
  name: 'lest',
  slug: 'now into ew',
  photo: 'trifling aw',
  thumbnail: 'squeeze raw oh',
  file: 'about',
  size: 'fatal until',
  sizeQty: 'black-and-white',
  sizePrice: 'recuperate',
  color: 'fuchsia',
  price: 17103.11,
  previousPrice: 499.86,
  details: 'phooey zowie',
  stock: 26219,
  policy: 'monthly mellow',
  status: 25373,
  views: 31281,
  tags: 'outlying repulsive beyond',
  features: 'shakily',
  colors: 'indeed esteemed',
  productCondition: 548,
  ship: 'ambitious',
  isMeta: true,
  metaTag: 'than wetsuit',
  metaDescription: 'angrily phooey yum',
  youtube: 'ophthalmologist',
  type: 'while nautical generally',
  license: 'fooey',
  licenseQty: 'courageously like',
  link: 'recklessly',
  platform: 'dodge triple shoelace',
  region: 'geez times',
  licenceType: 'whoever',
  measure: 'quizzically rarely supposing',
  featured: false,
  best: false,
  top: false,
  hot: true,
  latest: true,
  big: true,
  trending: false,
  sale: true,
  createdAt: dayjs('2023-12-02T13:11'),
  updatedAt: dayjs('2023-12-02T15:11'),
  isDiscount: true,
  discountDate: 'how',
  wholeSellQty: 'televise oof',
  wholeSellDiscount: 'skyjack courageously',
  isCatalog: true,
  catalogId: 26727,
};

export const sampleWithNewData: NewProducts = {
  name: 'doubtfully over',
  photo: 'yippee',
  price: 21570.72,
  status: 16118,
  views: 8992,
  productCondition: 26356,
  isMeta: true,
  type: 'ugh thumb',
  featured: false,
  best: false,
  top: true,
  hot: true,
  latest: true,
  big: true,
  trending: true,
  sale: false,
  isDiscount: false,
  isCatalog: true,
  id: null,
};

Object.freeze(sampleWithNewData);
Object.freeze(sampleWithRequiredData);
Object.freeze(sampleWithPartialData);
Object.freeze(sampleWithFullData);
